disableSerialization;
_display = findDisplay 50100;
_listbox = _display displayCtrl 50101;
_index = lbCurSel _listbox;
if (_index==-1) exitWith {hint "ERROR";};
_law = _listbox lbData _index;
diag_log format ["%1",_law];
[[_law],"TON_fnc_deleteLaw",false,false] spawn life_fnc_mp;
hint "The law has been removed";
closeDialog 0;