AH_loaded = false;
[[0,player],"TON_fnc_SAH_reciever",false,false] spawn life_fnc_mp;
waitUntil {AH_loaded};
waitUntil {createDialog "AH_buy";};
disableSerialization;
_dialog = findDisplay 15100;
_myListbox = _dialog displayCtrl 15101;
//_myListbox lnbAddColumn 0.3;
//_myListbox lnbAddColumn 0.4;
//_myListbox lnbAddColumn 0.5;
{
	_curOffer = _x;
	_pid = _curOffer select 0;
	_item = _curOffer select 1;
	_price = _curOffer select 2;
	_seller = [_pid] call life_fnc_CAH_getPlayerObj;
	_myListbox lbAdd format ["%3 for %2 by %1",name _seller,_price,([_item] call VAS_fnc_fetchCfgDetails) select 1];
	//_myListbox lnbAddRow [format ["%1",([_item] call VAS_fnc_fetchCfgDetails) select 1],format ["%1",_price],format ["%1",_seller]];
	_myListbox lbSetPicture [(lbSize _myListbox)-1, ([_item] call VAS_fnc_fetchCfgDetails select 2)];
	_myListbox lbSetPictureColor [(lbSize _myListbox)-1, [1, 1, 1, 1]];
	_myListbox lbSetData [(lbSize _myListbox)-1,format ["%1",[_pid,_item,_price]]];
} forEach AH_offers;
hint "Successfully loaded offers";